### ISSUE TITLE
Night time has the same sky as daytime!

### ISSUE THREAD

**Issue by ElephantNipple** [CubeIR/Vanilla-RTX#12] opened 2022-10-31 01:44 UTC
It is always day time even when set to night. The mobs act normal as if it is night even though there is a sun instead of a moon

**Comment by CubeIR** [comment] 2022-10-31 21:46
Duplicate of [issue #10](https://github.com/CubeIR/Vanilla-RTX/issues/10)

**Closed by CubeIR** 2022-10-31 21:46 UTC
Labels: duplicate
